### ISSUE TITLE
Improvement: Allow multiple hydra with single maester

### ISSUE THREAD

**Issue by paulbdavis** [ory/hydra-maester#34]
To accommodate the use-case of having multiple hyrda instances running in a cluster while still being able to the maester.

Currently you can only set up one `--hydra-url` when you start the app. Running multiple copies would lead to undesired behavior.

I am working on a patch that would add `HydraURL`, `HydraPort`, and `HydraEndpoint` to the CRD in order to allow the client to decide which hydra to use for registration. The original CLI flags would still be used and would be used as the default if the added CRD properties are missing. Otherwise it would override the values with what is present on the CRD (so in general, one would only need to set `HydraURL` assuming the deployments standardize the other values)

**Comment by p-bakker** [comment]
If this improvement now already implemented by https://github.com/ory/hydra-maester/pull/35?

Asking because I wonder if this improvement is about having one hydra-maester in a cluster that has multiple hydra's running and then measter will create/update/delete the CRD's on all Hydra instances

The title (the way I read it) seems to suggest so, but looking what you write about your patch and the changes in https://github.com/ory/hydra-maester/pull/35 it seems more about being able to specify in the CRD in which Hydra instance the oAuth Client needs to be created

**Comment by paulbdavis** [comment]
It is the latter. This patch allows you to specify the hydra instance in the CR

Paul Davis
github.com/dangersalad
github.com/Paul Davis

**Comment by p-bakker** [comment]
ok, so this case should be closed then, cause it looks like you already implemented it, no?
